// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtu110Pw1Q9uvWvUEjCc30dEYdUiEo8v8',
    appId: '1:575455628342:web:d9531ce7d80c4525dfdc97',
    messagingSenderId: '575455628342',
    projectId: 'dummy-project-12ffb',
    authDomain: 'dummy-project-12ffb.firebaseapp.com',
    storageBucket: 'dummy-project-12ffb.appspot.com',
    measurementId: 'G-K9CXJ0V081',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzmVZ_JFVf3QaOXKkiRSVV2jpcrXGWBCk',
    appId: '1:575455628342:android:bc1dba1a214d2354dfdc97',
    messagingSenderId: '575455628342',
    projectId: 'dummy-project-12ffb',
    storageBucket: 'dummy-project-12ffb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtlOF-MepFTHFVYfe2QLI7vIbCmcDpQGM',
    appId: '1:575455628342:ios:2d9d2874957d13b4dfdc97',
    messagingSenderId: '575455628342',
    projectId: 'dummy-project-12ffb',
    storageBucket: 'dummy-project-12ffb.appspot.com',
    androidClientId: '575455628342-ietgkhu078gmv6u1co2hfakqtj2njqi5.apps.googleusercontent.com',
    iosClientId: '575455628342-3e6kh8ifbbp8orh72loutdu08smc6b1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtlOF-MepFTHFVYfe2QLI7vIbCmcDpQGM',
    appId: '1:575455628342:ios:6360fa04c0b0130bdfdc97',
    messagingSenderId: '575455628342',
    projectId: 'dummy-project-12ffb',
    storageBucket: 'dummy-project-12ffb.appspot.com',
    androidClientId: '575455628342-ietgkhu078gmv6u1co2hfakqtj2njqi5.apps.googleusercontent.com',
    iosClientId: '575455628342-ieekbl8iuu9upnj64p1j6fh9b8brbi8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
